apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boundarypass
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/KuragayalaAkhil/boundarypass-aws-eks.git
    targetRevision: main
    path: k8s
    directory:
      exclude: monitoring-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
