sonar.projectKey=KuragayalaAkhil_boundarypass-aws-eks
sonar.organization=kuragayalaakhil
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true