apiVersion: apps/v1
kind: Deployment
metadata:
  name: boundarypass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boundarypass
  template:
    metadata:
      labels:
        app: boundarypass
    spec:
      containers:
        - name: boundarypass
          image: kuragayalaakhil/boundarypass:c5c5a2d3427d54f4dd76abe3e7913612607d2cb4
          ports:
            - containerPort: 8000
