apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: boundarypass
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: boundarypass
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
