apiVersion: v1
kind: Service
metadata:
  name: boundarypass
  annotations:
    checkov.io/skip1: CKV_K8S_21=Service stays with the live application in the default namespace
  labels:
    app: boundarypass
spec:
  type: ClusterIP
  selector:
    app: boundarypass
  ports:
    - name: http
      port: 80
      targetPort: 8000
